[package]
name = "dc_team_splitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serenity = "0.12.0"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
